FROM alpine:3.22

RUN addgroup -g 1000 storage \
    && adduser -D -H -u 10001 suidu \
    && adduser suidu storage
USER suidu
COPY bin/suidu-api /usr/local/bin/suidu-api

EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/suidu-api"]
